const homeData=[
  {
    id:101,
    village:"Utmarchar Noyapara",
    title:"",
    description:"",
    urlToImage:"https://www.123rf.com/photo_135815904_the-green-trees-in-the-middle-of-the-meadow-behind-the-blue-sky-and-white-clouds-during-the-sunny.html",
    area:"noyapara",
    makeProgram:"I am Azim Islam. Home address Jamalpur, Dewangonj",
  link:"https://www.facebook.com/smazim.islam.08",
  },
  {
    urlToImage:"https://www.123rf.com/photo_58323790_big-tree-in-cornfield.html?is_plus=1",
  },
  {
    urlToImage:"https://www.123rf.com/photo_19873312_rice-field-with-sky-background.html?is_plus=1",
  },
    {
    urlToImage:"https://www.123rf.com/photo_129079045_green-field-in-the-morning-and-blue-sky-with-beautiful-cloud-at-agriculture-countryside-beautiful.html",
  },
    {
    urlToImage:"https://www.123rf.com/photo_126560720_the-straw-dry-in-the-field-with-a-sky-background.html",
  },
    {
    urlToImage:"https://www.123rf.com/photo_30133565_in-the-season-of-rice-in-asia-has-made-delivery-of-the-beautiful-scenery-i-see-the-bright-and-breezy.html?is_plus=1",
  },
    {
    urlToImage:"https://www.123rf.com/photo_77993750_arid-rajasthan-landscape-with-wheat-and-mustard-fields-amongst-sandy-scrub-with-acacia-trees-under-a.html",
  },
    {
    urlToImage:"https://www.123rf.com/photo_58713881_rice-field.html?is_plus=1",
  },
    {
    urlToImage:"https://www.123rf.com/photo_135232992_rice-fields-near-bogra-bangladesh.html",
  },
    {
    urlToImage:"https://www.123rf.com/photo_60671407_rural-scene-of-rice-field-green-grass-with-blue-sky-cloudy-landscape-background.html?is_plus=1",
  },
    {
    urlToImage:"https://dewangonj.jamalpur.gov.bd/en/site/top_banner/yzAc-%E0%A6%AF%E0%A6%AE%E0%A7%81%E0%A6%A8%E0%A6%BE-%E0%A6%A8%E0%A6%A6%E0%A7%80",
  },
    {
    urlToImage:"",
  },
    {
    urlToImage:"",
  },
    {
    urlToImage:"",
  },
    {
    urlToImage:"",
  },
    {
    urlToImage:"",
  },
    {
    urlToImage:"",
  },
    {
    urlToImage:"",
  },
  ];
  module.exports=homeData;